# DO NOT CHANGE THIS FILE MANUALLY
# SINCE THIS IS A TEMPLATE FILE
[global]
enable = "true"

[remote]
host = "your remote server"
port = 22
username = "remote server username"
protocal = "ssh" # we will add more protocal support in the future

# some enum values used by other configuration
[enum]
invoke_types = ["on_change", "on_exit_shell", "on_exit", "on_minutes"]
repo_status  = ["public", "private"]
commit_types = ["auto","manually"]


[[owned-repos]]
# repo_name = "" # will mapped to https://github.com/username/reponame
# local_path = "gh-sync" 
# sync_freq = 5
# if_owner = false
# if_activated = true
# commit_info = ""
# commit_trigger = "auto"

# for the local repos, you need to specify the absolute path of it
[[owned-repos]]
# repo_name = ""
# local_path = "/home/march1917/projects/rust/citybound"
# remote_path = ""
# sync_freq = 7
# is_on_gh = true
# if_activated = true
# commit_info = ""
# commit_trigger = "auto"

[[cooperation-repos]]


[[cooperation-repos]]


[[cloud-repos]]
# repo_name = ""
# sync_freq = 7
# is_on_gh = true
# if_activated = true
# commit_info = ""
# commit_trigger = "auto"
