# DO NOT CHANGE THIS FILE MANUALLY
# SINCE THIS IS A TEMPLATE FILE
[status]
enabled  = true
local_base = "" # where the folders from the remote downloads

[remote]
host = "your remote server"
port = 22
user_name = "remote server username"
# protocal = "ssh" # we will add more protocal support in the future
# default /home/username/git-sync
# remote_base = "" # where to store the repos in the remote


# some enum values used by other configuration
# [enum]
# sync_types   = ["on_change", "on_minutes", "on_close_file""]
# repo_status  = ["public", "private"]
# commit_types = ["auto", "manually"]


[[reps]]
repo_name    = "t_re" # will mapped to /home/$USERNAME/git-sync/repo_name
local_path   = "/path/to/repo" 
sync_type    = "on_exit"
sync_freq    = 5     # is valid when sync_type is on_change,1 by default 
if_owner     = false # if if_owner, it says it is synced from the remote
if_activated = true
added_time   = 1979-05-27T07:32:00Z 
synced_time   = 1979-05-27T07:32:00Z 

[[repos]]
repo_name    = "t_re_2" # will mapped to /home/$USERNAME/git-sync/repo_name
local_path   = "/path/to/repo" 
sync_type    = "on_exit"
sync_freq    = 5     # is valid when sync_type is on_change,1 by default 
if_owner     = false # if if_owner, it says it is synced from the remote
if_activated = true
added_time   = 1979-05-27T07:32:00Z 
synced_time   = 1979-05-27T07:32:00Z 
